

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('004',TO_DATE('2019-01-02','YYYY-MM-DD'),'1471156710','00235', 0.1);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('004','1000889',18,10);

DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT 
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM 
NOTAS N
INNER JOIN 
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

CREATE TRIGGER TG_TAB_FATURAMENTO
AFTER INSERT ON ITENS_NOTAS
BEGIN
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT 
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM 
NOTAS N
INNER JOIN 
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;
END;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('006',TO_DATE('2019-01-05','YYYY-MM-DD'),'1471156710','00235', 0.1);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('006','1000889',28,10);


SELECT* FROM TAB_FATURAMENTO;