CREATE TABLE NOTAS (
 CPF NVARCHAR2(11)
,MATRICULA NVARCHAR2(5)
,DATA_VENDA DATE
,NUMERO NUMBER (38,0)
,IMPOSTO FLOAT);

CREATE TABLE ITENS_NOTAS (
 NUMERO NUMBER (38,0)
,CODIGO_DO_PRODUTO NVARCHAR2 (10)
,QUANTIDADE NUMBER (38,0)
,PRECO FLOAT) ;


SELECT* FROM TABELA_DE_CLIENTES;
-- 1471156710
SELECT* FROM VENDEDORES;
-- 00235
SELECT* FROM PRODUTOS;
--1000889

SELECT* FROM NOTAS;
INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('001',TO_DATE('2019-01-01','YYYY-MM-DD'),'1471156710','00235', 0.1);

SELECT* FROM ITENS_NOTAS;

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('001','1000889',10,10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('002',TO_DATE('2019-01-01','YYYY-MM-DD'),'1471156710','00235', 0.1);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('002','1000889',15,10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('003',TO_DATE('2019-01-02','YYYY-MM-DD'),'1471156710','00235', 0.1);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('003','1000889',18,10);

SELECT* FROM NOTAS;
SELECT* FROM ITENS_NOTAS;

SELECT 
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM 
NOTAS N
INNER JOIN 
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;


CREATE TABLE TAB_FATURAMENTO (DATA_VENDA DATE NULL, FATURAMENTO FLOAT);

INSERT INTO TAB_FATURAMENTO
SELECT 
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM 
NOTAS N
INNER JOIN 
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;

SELECT* FROM TAB_FATURAMENTO;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('004',TO_DATE('2019-01-02','YYYY-MM-DD'),'1471156710','00235', 0.1);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_DO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('004','1000889',18,10);

DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT 
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM 
NOTAS N
INNER JOIN 
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;


