SELECT* FROM PRODUTOS WHERE CODIGO = 1040107;
UPDATE PRODUTOS SET PRECO = 5.2 WHERE CODIGO = 1040107;
UPDATE PRODUTOS SET EMBALAGEM = 'GARRAFA', TAMANHO = '1 L' WHERE CODIGO = 1040107;
SELECT NOME, REPLACE(NOME, 'Laranja', 'Maracuja') FROM PRODUTOS WHERE CODIGO = 1040107;
UPDATE PRODUTOS SET NOME = REPLACE(NOME, 'Laranja', 'Maracuja') WHERE CODIGO = 1040107;
UPDATE PRODUTOS SET SABOR = 'Maracuja' WHERE CODIGO = 1040107;

-- Para reajustar o preço de todos produtos que atendem a um requisito:

UPDATE PRODUTOS SET PRECO = PRECO *1.1 WHERE SABOR = 'Maracuja';
--

SELECT* FROM VENDEDORES V;
SELECT* FROM TABELA_DE_VENDEDORES_FONTE TVF;

SELECT V.MATRICULA AS MATRICULA_VENDEDORES
       ,TVF.MATRICULA AS MATRICULA_FONTE
       ,V.DE_FERIAS AS FERIAS_VENDEDORES
       ,TVF.DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V 
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF
ON SUBSTR(V.MATRICULA, 3,3) = TVF.MATRICULA;

SELECT V.MATRICULA AS MATRICULA_VENDEDORES
       ,TVF.MATRICULA AS MATRICULA_FONTE
       ,V.DE_FERIAS AS FERIAS_VENDEDORES
       ,TVF.DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V
RIGHT JOIN TABELA_DE_VENDEDORES_FONTE TVF 
ON SUBSTR(V.MATRICULA,3,3) = TVF.MATRICULA;
WHERE EXISTS
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF WHERE SUBSTR(V.MATRICULA,3,3)) = TVF.MATRICULA;

SELECT V.MATRICULA AS MATRICULA_VENDEDORES
       ,V.DE_FERIAS AS FERIAS_VENDEDORES
FROM VENDEDORES V
WHERE EXISTS 
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF WHERE SUBSTR(V.MATRICULA,3,3) = TVF.MATRICULA; 

SELECT V.MATRICULA AS MATRICULA_VENDEDORES
       ,TVF.MATRICULA AS MATRICULA_FONTE
       ,V.DE_FERIAS AS FERIAS_VENDEDORES
       ,TVF.DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF
ON SUBSTR(V.MATRICULA,3,3) = TVF.MATRICULA;

UPDATE VENDEDORES V SET V.DE_FERIAS =
(SELECT TVF.DE_FERIAS FROM TABELA_DE_VENDEDORES_FONTE TVF WHERE SUBSTR(V.MATRICULA,3,3) = TVF.MATRICULA)
WHERE EXISTS
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF WHERE SUBSTR(V.MATRICULA,3,3) = TVF.MATRICULA);

UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 1 WHERE MATRICULA IN ('236','237');

SELECT* FROM TABELA_DE_VENDEDORES_FONTE;

SELECT V.MATRICULA AS MATRICULA_VENDEDORES
      ,TVF.MATRICULA AS MATRICULA_FONTE
      ,V.DE_FERIAS AS FERIAS_VENDEDORES
      ,TVF.DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF
ON SUBSTR(V.MATRICULA,3,3) = TVF.MATRICULA;