SELECT* FROM PRODUTOS WHERE CODIGO_DO_PRODUTO = 1040107;

UPDATE PRODUTOS
SET PRECO_DE_LISTA = 4.6
WHERE CODIGO_DO_PRODUTO = 1040107;

SELECT NOME_DO_PRODUTO, REPLACE(NOME_DO_PRODUTO, 'Melancia', 'Laranja') FROM PRODUTOS WHERE CODIGO_DO_PRODUTO = 1040107;

UPDATE PRODUTOS 
SET NOME_DO_PRODUTO = REPLACE(NOME_DO_PRODUTO, 'Melancia', 'Laranja')
WHERE CODIGO_DO_PRODUTO = 1040107;


UPDATE PRODUTOS
SET SABOR = REPLACE(SABOR, 'Melancia', 'Laranja')
WHERE CODIGO_DO_PRODUTO = 1040107;