SELECT * FROM PRODUTOS;

SELECT NOME_DO_PRODUTO, PREO;



ALTER TABLE "TABELA_DE_VENDEDORES" RENAME TO VENDEDORES;
ALTER TABLE "PRODUTOS" RENAME COLUMN PRECO_DE_LISTA TO PRECO;
ALTER TABLE PRODUTOS RENAME COLUMN NOME_DO_PRODUTO TO NOME;
ALTER TABLE PRODUTOS RENAME COLUMN CODIGO_DO_PRODUTO TO CODIGO;
ALTER TABLE PRODUTOS
MODIFY COLUMN PRECO_DE_LISTA = PRECO;

UPDATE PRODUTOS
SET PRECO_DE_LISTA = PRECO;

SELECT* FROM TABELA_DE_VENDEDORES WHERE EXTRACT(YEAR FROM DATA_ADMISSAO);

SELECT* FROM PRODUTOS;
SELECT CODIGO, REPLACE(NOME, 'Uva', 'Tangerina') FROM PRODUTOS WHERE CODIGO = 1000889;

SELECT* FROM TABELA_DE_VENDEDORES ;

SELECT NOME, REPLACE(NOME, 'Almeida', 'Rapunzel') FROM TABELA_DE_VENDEDORES WHERE MATRICULA = 00235;

UPDATE TABELA_DE_VENDEDORES
SET NOME = REPLACE(NOME, 'Almeida', 'Rapunzel')
WHERE MATRICULA = 00235;

UPDATE TABELA_DE_VENDEDORES
SET NOME = REPLACE(NOME, 'Martins', 'Trovão')
WHERE MATRICULA = 00237;

SELECT* FROM PRODUTOS;

UPDATE PRODUTOS
SET REPLACE(NOME, 'Uva', 'Pessego');

UPDATE PRODUTOS SET PRECO =  PRECO * 1.10 WHERE SABOR = 'Uva';


CREATE TABLE "TABELA_DE_VENDEDORES_FONTE" 
   ("MATRICULA" NVARCHAR2(5), 
	"NOME" NVARCHAR2(100), 
	"PERCENTUAL_COMISSAO" FLOAT(126), 
	"DATA_ADMISSAO" DATE, 
	"DE_FERIAS" NUMBER(1,0), 
	"BAIRRO" NVARCHAR2(50)
   );

Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00235','Marcio Almeida Silva','0,08',to_date('15/08/14','DD/MM/RR'),'0','Tijuca');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00236','Claudia Morais','0,08',to_date('17/09/13','DD/MM/RR'),'1','Jardins');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00237','Roberta Martins','0,11',to_date('18/03/17','DD/MM/RR'),'1','Copacabana');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00238','Pericles Alves','0,11',to_date('21/08/16','DD/MM/RR'),'0','Santo Amaro');


SELECT* FROM VENDEDORES V;

SELECT* FROM TABELA_DE_VENDEDORES_FONTE TVF;
UPDATE TABELA_DE_VENDEDORES_FONTE
SET MATRICULA = 238
WHERE BAIRRO = 'Santo Amaro';

SELECT V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE,
V.DE_FERIAS AS FERIAS_VENDEDORES, TVF.DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF ON SUBSTR(V.MATRICULA, 3,3) = SUBSTR(TVF.MATRICULA, 3,3);

UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 0 WHERE MATRICULA IN ('00236','00237');

UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 1 WHERE MATRICULA IN ('00235','00238');